# Generated by Django 5.2 on 2025-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.TextField(blank=True, max_length=200, null=True)),
                ('symptoms', models.TextField(blank=True, max_length=200, null=True)),
                ('diagnosis', models.TextField(blank=True, max_length=200, null=True)),
                ('treatment', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
